<a href="https://colab.research.google.com/github/bryanpioloEspanol/-Linear-Algebra-58019/blob/main/midexam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Question 1. Create a Python code that displays a square matrix whose length is 5***

In [2]:
import numpy as np 
d= np.full((5,5),5)# square matrix
print(d)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


# ***Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero***

In [3]:
import numpy as np
g=np.zeros((5,5))
print(g)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## ***Question 3. Create a Python code that displays a square matrix which is symmetrical ***

In [4]:
import numpy as np
X= np.array([[1,2,3],[2,3,3],[3,4,-2]])
print ("Array is ",X)

W = np.transpose(X)
print("transpose is ", W)

Array is  [[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
transpose is  [[ 1  2  3]
 [ 2  3  4]
 [ 3  3 -2]]


# **`*Question 4. What is the inverse of matrix C? Show your solution by python coding.*`**

In [5]:
import numpy as np
C=np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(C)
inv_C=np.linalg.inv(C)
print(inv_C)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


# ***Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding.***

In [9]:
C=np.array([[1,2,3],[2,3,3],[3,4,-2]]) #array
print(C) # printing the array to see the result 
print ("Determinant matrix is:")
print(np.linalg.det(C)) # result without round 
print("Determinant with roundoff matrix is;" )
print(round(np.linalg.det(C))) # to round up the result

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
Determinant matrix is:
5.000000000000001
Determinant with roundoff matrix is;
5


# ***Question 6. Find the roots of the linear equations by showing its python codes (30 points)***
# ***5X1 + 4X2 + X3 = 3.4***
# ***10X1 + 9X2 + 4X3 = 8.8***
# **10X1 + 13X2 + 15X3 = 19.2**

In [10]:
import numpy as np 
A = np.array([[5,4,-1],[10,9,4],[10,13,15]])
print(A)
inv_A=np.linalg.inv(A)
print (inv_A)

B = np.array([[3,4],[8,8],[19,2,]])
print(B)

#AA"-1x _B.A"-1
X =np.dot(inv_A,B)
print(X)

[[ 5  4 -1]
 [10  9  4]
 [10 13 15]]
[[-1.27692308  1.12307692 -0.38461538]
 [ 1.69230769 -1.30769231  0.46153846]
 [-0.61538462  0.38461538 -0.07692308]]
[[ 3  4]
 [ 8  8]
 [19  2]]
[[-2.15384615  3.10769231]
 [ 3.38461538 -2.76923077]
 [-0.23076923  0.46153846]]
